name: viblify_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+21

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.15.0
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  firebase_storage: ^11.6.1
  giphy_get: ^3.5.4
  timeago: ^3.6.1
  flutter_des: ^2.2.0
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  like_button: ^2.0.5
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.7.0
  ionicons: ^0.2.2
  youtube_player_flutter: ^8.1.2
  file_picker: ^6.1.1
  line_icons: ^2.0.3
  page_transition: ^2.1.0
  intl: ^0.19.0
  linkable: ^3.0.2
  string_validator: ^1.0.2
  url_launcher: ^6.2.4
  panara_dialogs: ^0.1.4
  extended_image: ^8.2.0
  shimmer: ^3.0.0
  http: ^1.2.0
  simple_fontellico_progress_dialog: ^0.3.0
  fluttertoast: ^8.2.4
  saver_gallery: ^3.0.2
  permission_handler: ^11.2.0
  image_gallery_saver: ^2.0.3
  rxdart: ^0.27.7
  skeletonizer: ^1.0.1
  encrypt: ^5.0.0
  tuple: ^2.0.2
  html: ^0.15.4
  clipboard: ^0.1.3
  flutter_dotenv: ^5.1.0
  firebase_remote_config: ^4.3.14
  package_info_plus: ^5.0.1
  pub_semver: ^2.1.4
  go_router: ^13.2.0
  uuid: ^3.0.7
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.16
  flutter_notification_channel: ^2.0.0
  flutter_local_notifications: ^16.3.2
  image_cropper: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  zoom_tap_animation: ^1.1.0
  any_link_preview: ^3.0.1
  swipe_to: 1.0.4
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  custom_refresh_indicator: ^3.0.0
  firebase_analytics: ^10.8.8
  hexcolor: ^3.0.1
  google_mlkit_image_labeling: ^0.5.0
  supabase_flutter: ^2.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf
        - asset: assets/fonts/LobsterTwo-Bold.ttf
        - asset: assets/fonts/LobsterTwo-Italic.ttf
          style: italic
    - family: FixelDisplay
      fonts:
        - asset: assets/fonts/FixelDisplay-ExtraBold.ttf
          weight: 800
    - family: FixelText
      fonts:
        - asset: assets/fonts/FixelText-Bold.ttf
          weight: 700
        - asset: assets/fonts/FixelText-Medium.ttf
          weight: 500
        - asset: assets/fonts/FixelText-Regular.ttf
          weight: 400
        - asset: assets/fonts/FixelText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FixelText-ExtraBold.ttf
          weight: 800

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
